services:
  - type: web
    name: hashwei-telegram-bot
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8080
      - key: PYTHONUNBUFFERED
        value: 1
    autoDeploy: true
    buildCommand: ""
    startCommand: "./start.sh"
